"""initial schema

Revision ID: 27a5340a7625
Revises: 
Create Date: 2026-07-06 14:23:54.116675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27a5340a7625'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('tg_id')
    )
    op.create_table('bans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['tg_id'], ['users.tg_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tg_id')
    )
    op.create_table('complaints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('complainant_tg_id', sa.BigInteger(), nullable=False),
    sa.Column('reported_tg_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['complainant_tg_id'], ['users.tg_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reported_tg_id'], ['users.tg_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('complainant_tg_id', 'reported_tg_id', name='uq_complainant_reported')
    )
    op.create_table('dislikes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('disliker_tg_id', sa.BigInteger(), nullable=False),
    sa.Column('disliked_tg_id', sa.BigInteger(), nullable=False),
    sa.Column('until', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['disliked_tg_id'], ['users.tg_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['disliker_tg_id'], ['users.tg_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('disliker_tg_id', 'disliked_tg_id', name='uq_dislike_tg_id')
    )
    op.create_table('likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('liker_tg_id', sa.BigInteger(), nullable=False),
    sa.Column('liked_tg_id', sa.BigInteger(), nullable=False),
    sa.Column('is_accepted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.CheckConstraint('liker_tg_id != liked_tg_id', name='ck_no_self_like'),
    sa.ForeignKeyConstraint(['liked_tg_id'], ['users.tg_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['liker_tg_id'], ['users.tg_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('liker_tg_id', 'liked_tg_id', name='uq_liker_liked')
    )
    op.create_index(op.f('ix_likes_liked_tg_id'), 'likes', ['liked_tg_id'], unique=False)
    op.create_index(op.f('ix_likes_liker_tg_id'), 'likes', ['liker_tg_id'], unique=False)
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('sex', sa.Enum('MALE', 'FEMALE', name='sexenum'), nullable=False),
    sa.Column('town', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('s3_path', sa.String(length=1024), nullable=False),
    sa.Column('sex_filter', sa.Enum('OFF', 'ONLY_GIRLS', 'ONLY_BOYS', name='sex_filter_state'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tg_id'], ['users.tg_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tg_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profiles')
    op.drop_index(op.f('ix_likes_liker_tg_id'), table_name='likes')
    op.drop_index(op.f('ix_likes_liked_tg_id'), table_name='likes')
    op.drop_table('likes')
    op.drop_table('dislikes')
    op.drop_table('complaints')
    op.drop_table('bans')
    op.drop_table('users')
    # ### end Alembic commands ###
    sa.Enum(name='sexenum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='sex_filter_state').drop(op.get_bind(), checkfirst=True)