"""change likes fk from users to profile

Revision ID: beef7847d881
Revises: 27a5340a7625
Create Date: 2026-07-23 12:14:50.739522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'beef7847d881'
down_revision: Union[str, Sequence[str], None] = '27a5340a7625'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('complaints_complainant_tg_id_fkey'), 'complaints', type_='foreignkey')
    op.drop_constraint(op.f('complaints_reported_tg_id_fkey'), 'complaints', type_='foreignkey')
    op.create_foreign_key(None, 'complaints', 'profiles', ['reported_tg_id'], ['tg_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'complaints', 'profiles', ['complainant_tg_id'], ['tg_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('dislikes_disliker_tg_id_fkey'), 'dislikes', type_='foreignkey')
    op.drop_constraint(op.f('dislikes_disliked_tg_id_fkey'), 'dislikes', type_='foreignkey')
    op.create_foreign_key(None, 'dislikes', 'profiles', ['disliker_tg_id'], ['tg_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'dislikes', 'profiles', ['disliked_tg_id'], ['tg_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('likes_liker_tg_id_fkey'), 'likes', type_='foreignkey')
    op.drop_constraint(op.f('likes_liked_tg_id_fkey'), 'likes', type_='foreignkey')
    op.create_foreign_key(None, 'likes', 'profiles', ['liker_tg_id'], ['tg_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'likes', 'profiles', ['liked_tg_id'], ['tg_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'likes', type_='foreignkey')
    op.drop_constraint(None, 'likes', type_='foreignkey')
    op.create_foreign_key(op.f('likes_liked_tg_id_fkey'), 'likes', 'users', ['liked_tg_id'], ['tg_id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('likes_liker_tg_id_fkey'), 'likes', 'users', ['liker_tg_id'], ['tg_id'], ondelete='CASCADE')
    op.drop_constraint(None, 'dislikes', type_='foreignkey')
    op.drop_constraint(None, 'dislikes', type_='foreignkey')
    op.create_foreign_key(op.f('dislikes_disliked_tg_id_fkey'), 'dislikes', 'users', ['disliked_tg_id'], ['tg_id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('dislikes_disliker_tg_id_fkey'), 'dislikes', 'users', ['disliker_tg_id'], ['tg_id'], ondelete='CASCADE')
    op.drop_constraint(None, 'complaints', type_='foreignkey')
    op.drop_constraint(None, 'complaints', type_='foreignkey')
    op.create_foreign_key(op.f('complaints_reported_tg_id_fkey'), 'complaints', 'users', ['reported_tg_id'], ['tg_id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('complaints_complainant_tg_id_fkey'), 'complaints', 'users', ['complainant_tg_id'], ['tg_id'], ondelete='CASCADE')
    # ### end Alembic commands ###
